### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by forgotmeplease** [soarbear/Binance_triangle_arbitrage_bot#3]
Traceback (most recent call last):
  File "1.py", line 173, in <module>
    main()
  File "1.py", line 28, in main
    prices = get_prices(client)
  File "1.py", line 126, in get_prices
    prepared[primary][secondary] = 1/ask
ZeroDivisionError: float division by zero

**Comment by soarbear** [comment]
ask=0 means that you have not successfully obtained data from the server. The server sometimes does not respond properly. This happens especially when a large amount of access occurs or when access restrictions are applied.
