### ISSUE TITLE
Trade Error

### ISSUE THREAD

**Issue by batuhanhazarguler** [soarbear/Binance_triangle_arbitrage_bot#4]
Hello, I was testing your project live. but I got the following error. what should i do for this?

USDT->QUICK->BTC->USDT         0.1088% <- profit!
     USDT -> QUICK :        0.01769912
     QUICK -> BTC  :        0.00334100
     BTC  -> USDT :    16954.93000000
[info]sym:USDTQUICK,bas:USDT,BUY,tic:10.0,col:1000.0,ass:0.2124,qua:0.212,pri:56.50000000
[info]sym:QUICKBTC,bas:QUICK,SELL,tic:1000000.0,col:1000.0,ass:0.2118,qua:0.211,pri:0.00334100
**[info]exception:APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.**
[info]break at tri_count:0! as symbol:BTCUSDT
[info]tri_count #0 failed in 65.5581s@2022-12-03 22:38:50.584661
[info]tri_count/loop_count:0/225

**Comment by soarbear** [comment]
As reference,
1. Check binance.client for this error. For this repository, developers cannot support parts other than developer management and errors. Please take responsibility for your actions.
2. As a reference, access to the server may be restricted, for example, the number of accesses per unit time.

**Comment by batuhanhazarguler** [comment]
How can I do the number of accesses per unit time?

**Comment by soarbear** [comment]
ex, One of the methods is to try to increase the sleep time 0.2 to 10ms etc, that means sleep(0.2) in main to  sleep(10) .
